site_name: Brainlife Documentation
site_author: 'Soichi Hayashi'
site_url: 'https://brain-life.github.io/docs/'

# Repository
repo_name: 'brain-life/docs'
repo_url: 'https://github.com/brain-life/docs'

copyright: 'Copyright &copy; 2017 - 2018 Brainlife.io'

theme:
  name: 'material'
  favicon: '/img/favicon.ico'
  palette:
    primary: 'light blue'

pages:
  - Home: index.md
  - About: about.md
  - Brainlife UI:
    - Tutorial: user/tutorial.md
    - Projects: user/project.md
    - Datatypes: user/datatypes.md
    - Processes: user/process.md
    - Pipelines: user/pipeline.md
    - Publications: user/publication.md
  - App Developers: 
    - Introduction: apps/introduction.md
    - HelloWorld: apps/helloworld.md
    - Registering App: apps/register.md
    - Containerizing App: apps/container.md
    - Versioning Tips: apps/versioning.md
    - Custom Hooks: apps/customhooks.md
    - product.json: apps/product.md
  - Resource Provider: 
    - Registering Resource: resources/register.md
  - Technical:
    - Architecture: technical/arthitecture.md
    - APIs: technical/api.md
  - Contact: contact.md
  - Privacy Policy: privacy.md
  - Releases: releases.md

extra:
  disqus: 'brain-life'
  social:
    - type: 'github'
      link: 'https://github.com/brain-life'
    - type: 'twitter'
      link: 'https://twitter.com/BrainLifeio'
markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - fontawesome_markdown
