site_name: brainlife Documentation
site_author: 'Soichi Hayashi'
site_url: https://brainlife.io/docs

# Repository
repo_name: 'brainlife/docs'
repo_url: 'https://github.com/brainlife/docs'

copyright: 'Copyright &copy; 2017 - 2019 brainlife.io'

theme:
  name: 'material'
  favicon: '/img/favicon.ico'
  palette:
    primary: 'light blue'

nav:
  - Home: index.md

  - Using brainlife:
    - Getting Started: user/started.md
    - Projects: user/project.md
    - Datatypes: user/datatypes.md
    - Processes: user/process.md
    - Pipelines: user/pipeline.md
    - Publications: user/publication.md

  - Tutorials: 
    - Tractometry: tutorial/diffusion-and-tractography.md
    - Structural networks: tutorial/networkneuroscience-structural.md
    - Functional networks: tutorial/networkneuroscience-functional.md
    
  - Developing Apps: 
    - Introduction: apps/introduction.md
    - HelloWorld: apps/helloworld.md
    - Registering App: apps/register.md
    - Containerizing App: apps/container.md
    - Versioning Tips: apps/versioning.md
    - Custom Hooks: apps/customhooks.md
    - product.json: apps/product.md

  - CLI:
    - Installation: cli/install.md
    - Uploading Dataset: cli/upload.md
    - Running Apps: cli/app.md
    - Downloading Datasets: cli/download.md

  - Compute Resources: 
    - Registering Resource: resources/register.md

  - Technical:
    - Architecture: technical/arthitecture.md
    - APIs: technical/api.md

  - Contact: contact.md
  - Privacy Policy: privacy.md
  - Media / Branding: media.md
#  - Releases: releases.md

extra:
  disqus: 'brain-life'
  social:
    - type: 'github'
      link: 'https://github.com/brainlife'
    - type: 'twitter'
      link: 'https://twitter.com/BrainLifeio'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
        permalink: True
  - fontawesome_markdown


